"""Generate LaTeX tables for the manuscript directly from the verified result
CSVs (results/refined_reference_cases.csv, results/refined_equilibria.csv).

Run from anywhere:  python paper/make_tables.py
Outputs booktabs tables into paper/tables/. No numeric value is hand-typed in
the manuscript; everything traces back to the CSVs produced by the (unchanged)
research code.
"""

from __future__ import annotations

import math
import os

import pandas as pd

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, ".."))
RESULTS = os.path.join(ROOT, "results")
TABLES = os.path.join(HERE, "tables")
os.makedirs(TABLES, exist_ok=True)

GEN_NOTE = ("% AUTO-GENERATED by paper/make_tables.py from results/*.csv. "
            "Do not edit by hand.\n")


def sci(v, sig=1):
    if v is None or (isinstance(v, float) and math.isnan(v)):
        return "--"
    if v == 0:
        return r"$<\!10^{-16}$"
    e = int(math.floor(math.log10(abs(v))))
    m = v / 10 ** e
    return rf"${m:.{sig}f}\times10^{{{e}}}$"


def smart(v, sig4=4):
    """Fixed notation for moderate magnitudes, scientific otherwise."""
    if v is None or (isinstance(v, float) and math.isnan(v)):
        return "--"
    a = abs(v)
    if a != 0 and (a < 1e-3 or a >= 1e4):
        return sci(v, sig=1)
    return f"${v:.4g}$"


def fx(v, dec):
    return f"${v:.{dec}f}$"


def disp(component):
    """Consistent display name for a CC component."""
    return {"Case1-arc": "Case-1 arc", "Case2-loop": "Case-2 arc"}.get(
        component, component)


def table_families(dfo, dff):
    """Summary of the actual computed periodic-orbit families."""
    m = dfo.merge(dff[["family_id", "member", "stability_index", "classification"]],
                  on=["family_id", "member"])
    lines = [
        r"\begin{table}[t]",
        r"\centering",
        r"\caption{Computed periodic-orbit families. Each family is a Lyapunov "
        r"family seeded from a simple centre mode of a parent equilibrium and "
        r"continued in amplitude; the Lyapunov centre theorem applies at every "
        r"parent (the exact non-resonance condition holds, including at the "
        r"saddle$\times$centre parents of families 5--6 and the near-resonant "
        r"parents of families 7--10; see Section~\ref{subsec:lyapunov}). What "
        r"differs is the parent stability type and proximity to resonance, not "
        r"theoretical standing. `mode' is the centre frequency "
        r"$\omega$; $N$ the number of corrected members; the $C_J$ and $T$ ranges "
        r"are over the family; `max closure' is the largest periodicity residual "
        r"$\|u(T)-u_0\|$ attained over the family's members (all $<10^{-10}$). "
        r"Floquet class is by the stability index $\nu$ ($|\nu|<2$ stable).}",
        r"\label{tab:periodic_families}",
        r"\footnotesize",
        r"\setlength{\tabcolsep}{3.5pt}",
        r"\begin{tabular}{clcccccl}",
        r"\toprule",
        r"Fam & parent (arc, eq.) & $\omega$ & $N$ & $C_J$ range & $T$ range "
        r"& max closure & Floquet / note \\",
        r"\midrule",
    ]
    labelmap = {"case1_stable": "Case-1 stable", "case2_stable": "Case-2 stable",
                "case1_saddlecentre": "Case-1 sdl$\\times$ctr",
                "case2_saddlecentre": "Case-2 sdl$\\times$ctr",
                "case1_res_3to2": "Case-1 $3{:}2$ reg.",
                "case2_res_2to1": "Case-2 $5{:}2$ reg."}
    for fid, g in m.groupby("family_id"):
        g = g.sort_values("amplitude")
        r0 = g.iloc[0]
        cls = g.classification.str.split(" \\(").str[0].mode().iloc[0]
        note = ""
        if "real unstable" in cls:
            note = "real unstable"
        elif (g.stability_index + 2).abs().min() < 0.02:
            note = f"Floquet stable; $\\nu\\!\\to\\!-2$"
        elif g.n_lobes.max() > 2:
            note = "Floquet stable; multi-lobe"
        else:
            note = "Floquet stable"
        parent = f"{labelmap.get(r0.label, r0.label)}, $({r0.x_eq:.2f},{r0.y_eq:.2f})$"
        lines.append(
            f"{fid} & {parent} & ${r0.omega_parent:.3f}$ & {len(g)} & "
            f"$[{g.jacobi_CJ.min():.2f},{g.jacobi_CJ.max():.2f}]$ & "
            f"$[{g['T'].min():.2f},{g['T'].max():.2f}]$ & "
            f"{sci(g.closure.max())} & "
            f"{note} \\\\")
    lines += [r"\bottomrule", r"\end{tabular}", r"\end{table}", ""]
    write("tab_families.tex", "\n".join(lines))


def write(name, text):
    path = os.path.join(TABLES, name)
    with open(path, "w", encoding="utf-8") as f:
        f.write(GEN_NOTE + text)
    print("wrote", os.path.relpath(path, ROOT))


def table_cases(dfc):
    lines = [
        r"\begin{table}[t]",
        r"\centering",
        r"\caption{The four representative non-symmetric configurations used as a "
        r"baseline. The approximate geometry is projected onto the "
        r"central-configuration manifold $\psi=0$ by a minimal single-coordinate "
        r"refinement (holding $a,b$ fixed); mass ratios are computed at the "
        r"refined geometry. $N_{\mathrm{eq}}$ is the equilibrium count located by "
        r"the independent global search (every root to $\|\nabla\Omega\|<10^{-12}$).}",
        r"\label{tab:cases}",
        r"\small",
        r"\setlength{\tabcolsep}{4pt}",
        r"\begin{tabular}{lcccccc}",
        r"\toprule",
        r"Case & $(a,b)$ & $(c_1,c_2)_{\mathrm{approx}}$ & "
        r"$(c_1,c_2)_{\mathrm{refined}}$ & $|\psi|_{\mathrm{refined}}$ & "
        r"$(\rho_0,\rho_1,\rho_2)$ & $N_{\mathrm{eq}}$ \\",
        r"\midrule",
    ]
    for _, r in dfc.iterrows():
        ab = f"$({r['a']:g},{r['b']:g})$"
        approx = f"$({r['c1_reference']:g},{r['c2_reference']:g})$"
        refined = f"$({r['c1_refined']:.6f},{r['c2_refined']:.6f})$"
        psires = sci(abs(r["psi_refined"]), sig=1)
        rho = f"$({r['rho0']:.5g},{r['rho1']:.5g},{r['rho2']:.5g})$"
        counts = f"${int(r['recomputed_count'])}$"
        lines.append(f"{r['case']} & {ab} & {approx} & {refined} & {psires} & "
                     f"{rho} & {counts} \\\\")
    lines += [r"\bottomrule", r"\end{tabular}", r"\end{table}", ""]
    write("tab_cases.tex", "\n".join(lines))


def table_refinement(dfc):
    lines = [
        r"\begin{table}[t]",
        r"\centering",
        r"\caption{Refinement of each approximate configuration onto $\psi=0$. "
        r"The single coordinate with the smaller displacement is adopted; the "
        r"alternative single-coordinate displacements and the distance to the "
        r"constrained nearest CC point (both coordinates free) are listed for "
        r"transparency.}",
        r"\label{tab:refinement}",
        r"\small",
        r"\begin{tabular}{lccccccc}",
        r"\toprule",
        r"Case & var & $\Delta$ & $|\psi|_{\mathrm{before}}$ & "
        r"$|\psi|_{\mathrm{after}}$ & $\Delta c_1^{\mathrm{opt}}$ & "
        r"$\Delta c_2^{\mathrm{opt}}$ & min-norm \\",
        r"\midrule",
    ]
    for _, r in dfc.iterrows():
        lines.append(
            f"{r['case']} & ${r['refined_var']}$ & {sci(r['refined_delta'])} & "
            f"{sci(abs(r['psi_reference']))} & {sci(abs(r['psi_refined']))} & "
            f"{sci(r['delta_c1_option'])} & {sci(r['delta_c2_option'])} & "
            f"{sci(r['min_norm_distance'])} \\\\"
        )
    lines += [r"\bottomrule", r"\end{tabular}", r"\end{table}", ""]
    write("tab_refinement.tex", "\n".join(lines))


def table_equilibria(dfe):
    lines = [
        r"\begin{table}[t]",
        r"\centering",
        r"\caption{Independently recomputed equilibria at the refined "
        r"configurations. Each root satisfies $\|\nabla\Omega\|<10^{-12}$. "
        r"$D=\det \mathrm{H}\Omega=\Omega_{xx}\Omega_{yy}-\Omega_{xy}^2$; "
        r"$C_J=2\Omega$ is the adopted Jacobi value at the equilibrium; "
        r"$\max\operatorname{Re}\lambda$ is taken over the four eigenvalues of "
        r"the variational matrix. `Unstable' denotes $\max\operatorname{Re}"
        r"\lambda>10^{-8}$; `spectrally stable' denotes a purely imaginary "
        r"spectrum (linear statement only).}",
        r"\label{tab:equilibria}",
        r"\footnotesize",
        r"\setlength{\tabcolsep}{4pt}",
        r"\begin{tabular}{llrrccrl}",
        r"\toprule",
        r"Case & $i$ & $x$ & $y$ & $\|\nabla\Omega\|$ & $D$ & "
        r"$\max\operatorname{Re}\lambda$ & class \\",
        r"\midrule",
    ]
    prev = None
    for _, r in dfe.iterrows():
        if prev is not None and r["case"] != prev:
            lines.append(r"\midrule")
        prev = r["case"]
        cls = "spectrally stable" if bool(r["stable"]) else "unstable"
        lines.append(
            f"{r['case']} & {int(r['index'])} & "
            f"${r['x']:.5f}$ & ${r['y']:.5f}$ & "
            f"{sci(r['grad_residual'])} & {smart(r['hessian_det'])} & "
            f"{smart(r['max_real_part'])} & {cls} \\\\"
        )
    lines += [r"\bottomrule", r"\end{tabular}", r"\end{table}", ""]
    write("tab_equilibria.tex", "\n".join(lines))


def table_bifurcations(dfb):
    lines = [
        r"\begin{table}[t]",
        r"\centering",
        r"\caption{Verified bifurcations along the two admissible "
        r"central-configuration arcs. Interior count changes are generic "
        r"saddle-node folds, located from the augmented system "
        r"$\Ox=\Oy=\det\mathrm{H}\Om=0$ with $\psi=0$; $\mu_{\min},\mu_{\max}$ "
        r"are the Hessian eigenvalues at the critical point, $\alpha$ the "
        r"transversality and $\beta$ the quadratic-nondegeneracy coefficient. "
        r"The folds are labelled $F_1$--$F_7$ in the same order as in "
        r"Figure~\ref{fig:ccpath} ($F_1,F_2$ on the Case-1 arc; $F_3$--$F_7$ on "
        r"the Case-2 arc, by increasing $s_c$). The $5\!\to\!4$ Case-1 event is a "
        r"mass-vanishing boundary ($\rho_2\to0$), not a fold.}",
        r"\label{tab:bifurcations}",
        r"\footnotesize",
        r"\setlength{\tabcolsep}{4pt}",
        r"\begin{tabular}{llcccccc}",
        r"\toprule",
        r"Arc & $N_{eq}$ & fold & $s_c$ & $(c_1,c_2)_c$ & "
        r"$(\rho_0,\rho_1,\rho_2)_c$ & $(\alpha,\beta)$ & type \\",
        r"\midrule",
    ]
    prev = None
    fold_k = 0
    for _, r in dfb.iterrows():
        if prev is not None and r["component"] != prev:
            lines.append(r"\midrule")
        prev = r["component"]
        arc = disp(r["component"])
        if "saddle-node" in str(r["classification"]):
            fold_k += 1
            fid = f"$F_{{{fold_k}}}$"
            cc = f"$({r['c1_c']:.4f},{r['c2_c']:.4f})$"
            rho = f"$({r['rho0_c']:.3g},{r['rho1_c']:.3g},{r['rho2_c']:.3g})$"
            ab = f"$({r['alpha']:.3g},{r['beta']:.3g})$"
            typ = "saddle-node"
        else:
            fid = "--"
            cc = rho = ab = "--"
            typ = "boundary ($\\rho_2\\!\\to\\!0$)"
        lines.append(f"{arc} & {r['count_change']} & {fid} & ${r['s_c']:.3f}$ & "
                     f"{cc} & {rho} & {ab} & {typ} \\\\")
    lines += [r"\bottomrule", r"\end{tabular}", r"\end{table}", ""]
    write("tab_bifurcations.tex", "\n".join(lines))


def table_po_candidates(dfp, n=8):
    lines = [
        r"\begin{table}[t]",
        r"\centering",
        r"\caption{Top-ranked centre-mode equilibria for future periodic-orbit "
        r"continuation (ranked by centre-mode interval width, favouring "
        r"purely-imaginary spectra). `centre2' denotes a spectrally stable "
        r"(two-centre) interval; `saddle$\times$centre' a single centre pair. "
        r"$\omega_1,\omega_2$ are centre frequencies at the representative "
        r"point; $C_J=2\Om$. Eigenvectors and continuation parameters "
        r"$(c_1,c_2,s)$ for each are stored in "
        r"\texttt{results/periodic\_orbit\_candidates.csv}.}",
        r"\label{tab:pocands}",
        r"\footnotesize",
        r"\setlength{\tabcolsep}{4pt}",
        r"\begin{tabular}{clccccc}",
        r"\toprule",
        r"rank & arc / type & $s$-interval & $(c_1,c_2)_{\mathrm{rep}}$ & "
        r"$\omega_1$ & $\omega_2$ & $C_J$ \\",
        r"\midrule",
    ]
    for _, r in dfp.head(n).iterrows():
        arc = disp(r["component"])
        typ = "c2" if str(r["type"]).startswith("centre2") else r"s$\times$c"
        interval = f"$[{r['s_lo']:.3f},{r['s_hi']:.3f}]$"
        cc = f"$({r['c1']:.3f},{r['c2']:.3f})$"
        om1 = f"${r['omega1']:.3f}$" if pd.notna(r['omega1']) else "--"
        om2 = f"${r['omega2']:.3f}$" if pd.notna(r['omega2']) else "--"
        lines.append(f"{int(r['rank'])} & {arc} ({typ}) & {interval} & {cc} & "
                     f"{om1} & {om2} & ${r['jacobi_CJ']:.3f}$ \\\\")
    lines += [r"\bottomrule", r"\end{tabular}", r"\end{table}", ""]
    write("tab_po_candidates.tex", "\n".join(lines))


def main():
    dfc = pd.read_csv(os.path.join(RESULTS, "refined_reference_cases.csv"))
    dfe = pd.read_csv(os.path.join(RESULTS, "refined_equilibria.csv"))
    table_cases(dfc)
    table_refinement(dfc)
    table_equilibria(dfe)
    bpath = os.path.join(RESULTS, "bifurcation_points.csv")
    if os.path.exists(bpath):
        table_bifurcations(pd.read_csv(bpath))
    ppath = os.path.join(RESULTS, "periodic_orbit_candidates.csv")
    if os.path.exists(ppath):
        table_po_candidates(pd.read_csv(ppath))
    opath = os.path.join(RESULTS, "periodic_orbits.csv")
    fpath = os.path.join(RESULTS, "periodic_orbit_floquet.csv")
    if os.path.exists(opath) and os.path.exists(fpath):
        table_families(pd.read_csv(opath), pd.read_csv(fpath))


if __name__ == "__main__":
    main()
